name: Java CI

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: nelonoel/branch-name@v1.0.1

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '21.2.0'
          java: 'java11'
          arch: 'amd64'

      - name: Install native-image component
        run: gu install native-image

      - name: Install Octopus Deploy CLI
        uses: OctopusDeploy/install-octocli@v1
        with:
          version: 7.4.3124

      - name: Checkstyle
        run: mvn --batch-mode checkstyle:checkstyle

      - name: Update version
        run: mvn versions:set -DnewVersion=0.1.${{ github.run_number }}

      - name: List dependencies
        run: mvn --batch-mode dependency:tree --no-transfer-progress

      - name: Install modules
        run: mvn --batch-mode install

      - name: Build with Maven
        run: mvn --batch-mode package --file pom.xml -Pnative

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 0.1.${{ github.run_number }}
          release_name: Release 0.1.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: JenkinsPipelineBuilderGithubBackend/target/jenkinspipelinebuildergithubbackend-runner
          asset_name: jenkinspipelinebuildergithubbackend-runner
          asset_content_type: application/octet-stream